language: python
python:
    - "2.7"
    - "2.6"

install: pip install -r test-requirements.txt --use-mirrors
script: tox
language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=pep8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
